### ISSUE TITLE
"error Cannot find symbol for Custom app react symbols" and spotify doesnt load in.

### ISSUE THREAD

**Issue by jeovanny315** [Daksh777/SpotifyNoPremium#13]
![image](https://user-images.githubusercontent.com/79304571/125873098-c733f134-ce2f-4ccc-9755-4ac99eb81ed8.png)
![image](https://user-images.githubusercontent.com/79304571/125873106-d189455b-b07c-4822-937b-25040a206970.png)

**Comment by Daksh777** [comment]
Hey,

This is a known bug with Spicetify CLI itself. Although there is no fix BUT there is a workaround.  
Download this old version: https://spotify.en.uptodown.com/windows/download/3764443 (1.1.62.583.gdac868ed-a)
Then go to `%AppData%/Local/Spotify` and create a folder named Update and change the properties of that folder to deny access to all user groups.

Also, check https://github.com/khanhas/spicetify-cli/issues/845

I'll pin this issue and add this issue to the README for other users.

**Comment by SapitoSucio** [comment]
Thank you, @Daksh777  folllowed your instructions and now everything working flawlessly 🐸

**Comment by peaillaud** [comment]
Hi, even with the version you provided, I still have this error... Any workaround ? Should I downgrade again ?

**Comment by peaillaud** [comment]
Tested on 1.1.59.714 and it doesn't work either.

**Comment by Daksh777** [comment]
> Hi, even with the version you provided, I still have this error... Any workaround ? Should I downgrade again ?

Did you accidentally restore the spicetify backup? It works for me on 1.1.62.583.gdac868ed-a and should also work for you regardless.

**Comment by peaillaud** [comment]
Okay I think I did things wrong, it works now. Thank you!

**Comment by Daksh777** [comment]
Thanks to @itsmeow, this issue has got a fix https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-891443909. I've updated the script to include the fix and you can now update to the latest Spotify version.
However, I'll keep this open until an official fix is applied.

**Comment by Daksh777** [comment]
Can someone confirm if this theme works on the new update (1.1.66.578.gc54d0f69-a)?
I've updated the CSS and the scripts.

**Comment by MathewJake365** [comment]
Yes it works. Thank you.

**Comment by SapitoSucio** [comment]
I'm on a virtual machine, I installed latest Spotify version (1.1.67.586.gbb5ef64e) and tried to do a fresh mod.
When the mod is running, I get this error "error Cannot find symbol for Custom app React symbols". 
When I open Spotify I get this message.

I have tried downloading some old versions but none of them works correctly.

I'm on spicetify v2.6.2
![image](https://user-images.githubusercontent.com/7357354/133280769-a4fcb2d5-e40e-4ede-a3d7-83cade4672f9.png)

**Comment by Daksh777** [comment]
I don't recommend using an older version unless specifically stated by me.
My Spotify works perfectly fine on Spotify for `1.1.67.586.gbb5ef64e`. Could you try reinstalling Spotify and removing any custom apps and extensions from Spicetify?

**Comment by SapitoSucio** [comment]
> My Spotify works perfectly fine on Spotify for `1.1.67.586.gbb5ef64e`. Could you try reinstalling Spotify and removing any custom apps and extensions from Spicetify?

It's weird because this is literally a new and fresh windows 10 installation, the onlyu thing I installed was Git from their webpage, I downloaded spicetify through your script when it asked if I had it and that's all.  
I have no custom apps or extension from Spicetify.

**Comment by Daksh777** [comment]
> It's weird because this is literally a new and fresh windows 10 installation, the onlyu thing I installed was Git from their webpage, I downloaded spicetify through your script when it asked if I had it and that's all.
> I have no custom apps or extension from Spicetify.

That's weird. How about you try uninstalling Spotify and follow the manual instructions and see if that works?
